{
 "title": "OpenWrt Wi-Fi Dashboard",
 "description": "OpenWrt Wi-Fi dashboard via prometheus-node-exporter-lua",
 "tags": [
  "OpenWrt",
  "Wi-Fi"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Wi-Fi Network Signal",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "wifi_network_signal_dbm", "legendFormat": "{{interface}}" }
   ]
  },
  {
   "title": "Wi-Fi Network Noise",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    { "expr": "wifi_network_noise_dbm", "legendFormat": "{{interface}}" }
   ]
  },
  {
   "title": "Wi-Fi Clients Throughput",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kbps" } },
   "targets": [
    {
     "expr": "sum by(station)(rate(wifi_station_transmit_kilobits_per_second[1m]))",
     "legendFormat": "TX {{station}}"
    },
    {
     "expr": "sum by(station)(rate(wifi_station_receive_kilobits_per_second[1m]))",
     "legendFormat": "RX {{station}}"
    }
   ]
  },
  {
   "title": "Connected Wi-Fi Clients",
   "type": "stat",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(wifi_station_signal_dbm, \"mac\", \"\", \"mac\")"
    }
   ]
  },
  {
   "title": "Wi-Fi Clients Inactivity (ms)",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "expr": "wifi_station_inactive_milliseconds"
    }
   ]
  },
  {
   "title": "Wi-Fi Clients Signal",
   "type": "table",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 18 },
   "targets": [
    { "expr": "wifi_station_signal_dbm" }
   ]
  }
 ]
}